apiVersion: 1

datasources:
  - name: InfluxDB-DCIM
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mtechlabs
      defaultBucket: dcim
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
    editable: false
